# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='atestat',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gradebook',
            field=models.CharField(default='01', max_length=16, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_card',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
