# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-23 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_system', '0002_auto_20171223_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adress',
        ),
    ]
